<?php

return [

    // Módulo 1
    1 => [
        [
            'title' => 'Misión, Visión y Política de Calidad',
            'objective' => 'Comprender la relación entre la misión, visión y la política de calidad con los procesos misionales.',
            'description' => 'Análisis detallado de cómo los elementos estratégicos guían la operación del servicio farmacéutico.',
            'duration' => 180,
            'order' => 1,
            'content' => '{"text": "Contenido teórico-práctico sobre formulación y alineación estratégica."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Clasificación de Procesos',
            'objective' => 'Diferenciar procesos estratégicos, misionales y de soporte.',
            'description' => 'Creación del mapa general del servicio farmacéutico y su contexto normativo.',
            'duration' => 180,
            'order' => 2,
            'content' => '{"text": "Taller guiado para mapear procesos de la droguería."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Mapa general del proceso misional',
            'objective' => 'Diseñar el mapa de procesos del servicio farmacéutico, identificando las interacciones clave entre ellos.',
            'description' => 'Exploración de cómo los procesos misionales se conectan para entregar valor al cliente, desde la adquisición hasta la dispensación.',
            'duration' => 180,
            'order' => 3,
            'content' => '{"text": "En esta lección, se construirá un diagrama visual que represente el flujo de trabajo principal. Se analizarán las entradas y salidas de cada proceso misional, como Selección, Adquisición, Recepción, Almacenamiento y Dispensación, para entender su secuencia lógica y dependencias. Se utilizarán herramientas de mapeo para visualizar cuellos de botella y oportunidades de mejora."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Interrelación con procesos estratégicos y de soporte',
            'objective' => 'Analizar cómo los procesos de apoyo (RR.HH., Mantenimiento) y estratégicos (Planeación) habilitan la operación misional.',
            'description' => 'Estudio de la sinergia entre los diferentes tipos de procesos para garantizar la calidad y la eficiencia operativa.',
            'duration' => 180,
            'order' => 4,
            'content' => '{"text": "Se discutirá el rol de la Planeación y Gerencia en la definición de objetivos, y cómo el área de Saneamiento y Mantenimiento asegura las condiciones óptimas para la operación. Se analizará el impacto de la gestión de Recurso Humano en la competencia del personal que ejecuta los procesos misionales."}',
            'video_url' => null,
            'iframe' => null,
        ],
    ],

    // Módulo 2
    2 => [
        [
            'title' => 'Proveedores y Criterios de Selección',
            'objective' => 'Identificar criterios de selección y homologación de proveedores.',
            'description' => 'Buenas prácticas y cumplimiento normativo en la adquisición de medicamentos.',
            'duration' => 180,
            'order' => 1,
            'content' => '{"text": "Checklist para auditoría de proveedores."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Entradas y registros obligatorios',
            'objective' => 'Implementar registros correctos y control de riesgos de abastecimiento.',
            'description' => 'Gestión documental y prevención de quiebres de inventario.',
            'duration' => 180,
            'order' => 2,
            'content' => '{"text": "Estudio de caso de riesgo en compras."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Actividades del proceso de compras',
            'objective' => 'Detallar el ciclo completo de una orden de compra, desde la solicitud hasta la confirmación.',
            'description' => 'Un recorrido paso a paso por las actividades operativas del proceso de adquisición, asegurando la trazabilidad y el control.',
            'duration' => 180,
            'order' => 3,
            'content' => '{"text": "Esta lección cubre la generación de la orden de compra, el envío al proveedor, el seguimiento de la confirmación y la coordinación con el área de recepción. Se revisarán los formatos y sistemas utilizados para registrar cada etapa, asegurando que la información sea precisa y esté disponible para auditorías."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Salidas, indicadores de gestión y puntos críticos',
            'objective' => 'Identificar las salidas clave del proceso de adquisición y los indicadores para medir su desempeño.',
            'description' => 'Análisis de los resultados del proceso, como facturas y productos solicitados, y cómo medir la eficiencia a través de KPIs como el tiempo de entrega y el cumplimiento del proveedor.',
            'duration' => 180,
            'order' => 4,
            'content' => '{"text": "Se definirán indicadores como \'Porcentaje de cumplimiento de entrega de proveedores\' y \'Tiempo promedio de ciclo de compra\'. Se identificarán puntos críticos como la negociación de precios y la gestión de plazos de entrega, y cómo estos afectan la disponibilidad del producto."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Gestión del riesgo en compras y abastecimiento',
            'objective' => 'Identificar y mitigar los riesgos asociados a la cadena de suministro farmacéutico.',
            'description' => 'Estrategias para manejar riesgos como quiebres de stock, proveedores no confiables, fluctuaciones de precios y problemas de calidad en la adquisición.',
            'duration' => 180,
            'order' => 5,
            'content' => '{"text": "Se presentará una matriz de riesgos para el proceso de compras. Se analizarán casos prácticos sobre cómo diversificar proveedores, establecer acuerdos de nivel de servicio (SLA) y crear planes de contingencia para productos críticos, garantizando la continuidad del servicio al paciente."}',
            'video_url' => null,
            'iframe' => null,
        ],
    ],

    // Módulo 3
    3 => [
        [
            'title' => 'Procedimientos de recepción y verificación documental',
            'objective' => 'Aplicar protocolos de recepción y verificación documental.',
            'description' => 'Control de calidad y checklists para recepción de pedidos.',
            'duration' => 180,
            'order' => 1,
            'content' => '{"text": "Simulación de recepción de proveedores con protocolos."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Control de calidad y registros de recepción',
            'objective' => 'Aplicar técnicas de inspección visual y organoléptica para asegurar la calidad de los productos recibidos.',
            'description' => 'Protocolos para la verificación de la integridad del empaque, fechas de vencimiento, registro sanitario y características del producto. Diligenciamiento del acta de recepción técnica.',
            'duration' => 180,
            'order' => 2,
            'content' => '{"text": "Esta lección detalla el proceso de inspección física de medicamentos y dispositivos médicos. Se enseñará a documentar cualquier no conformidad en el acta de recepción técnica y a gestionar la cuarentena de productos sospechosos hasta su clarificación con el proveedor."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Métodos de almacenamiento (FEFO, FIFO, temperatura, humedad)',
            'objective' => 'Organizar productos con criterios FEFO y FIFO.',
            'description' => 'Control de temperatura, humedad y seguridad.',
            'duration' => 180,
            'order' => 3,
            'content' => '{"text": "Planos de almacenamiento y análisis de riesgos."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Indicadores, puntos críticos y riesgos del proceso',
            'objective' => 'Evaluar la eficiencia y seguridad de los procesos de recepción y almacenamiento a través de indicadores clave.',
            'description' => 'Análisis de KPIs como \'Exactitud del inventario\', \'Cumplimiento de la cadena de frío\' y \'Número de no conformidades en recepción\'. Identificación de riesgos como daños, pérdidas y vencimientos.',
            'duration' => 180,
            'order' => 4,
            'content' => '{"text": "Se definirán y calcularán indicadores para monitorear el desempeño del almacenamiento. Se identificarán puntos críticos como el control de temperatura y la segregación de productos. Se discutirán estrategias para mitigar riesgos como el deterioro de productos y las desviaciones de inventario."}',
            'video_url' => null,
            'iframe' => null,
        ],
    ],

    // Módulo 4
    4 => [
        [
            'title' => 'Dispensación Básica',
            'objective' => 'Definir tipos de dispensación y requisitos normativos.',
            'description' => 'Claves para la entrega correcta y segura de medicamentos.',
            'duration' => 180,
            'order' => 1,
            'content' => '{"text": "Procedimientos y formatos para dispensación."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Entradas (receta médica, solicitud de usuario) y registros',
            'objective' => 'Validar correctamente las recetas médicas y registrar las dispensaciones según la normativa.',
            'description' => 'Procedimiento para la interpretación de fórmulas médicas, verificación de datos del paciente y del prescriptor, y registro obligatorio de la dispensación en los sistemas correspondientes.',
            'duration' => 180,
            'order' => 2,
            'content' => '{"text": "Se analizarán los elementos obligatorios de una receta médica. Se practicará el diligenciamiento de los registros de dispensación, incluyendo el control de medicamentos de control especial y la documentación de la entrega al paciente o acudiente."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Atención y Satisfacción',
            'objective' => 'Fomentar uso seguro y fidelización del cliente.',
            'description' => 'Técnicas de comunicación farmacéutica y encuestas de satisfacción.',
            'duration' => 180,
            'order' => 3,
            'content' => '{"text": "Roleplay de atención farmacéutica."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Indicadores, riesgos y su relación con la satisfacción del cliente',
            'objective' => 'Medir el impacto del proceso de dispensación en la satisfacción del usuario y gestionar los riesgos asociados.',
            'description' => 'Análisis de indicadores como \'Tiempo de espera en dispensación\', \'Errores de dispensación\' y \'Nivel de satisfacción del usuario\'. Identificación de riesgos como la entrega incorrecta de medicamentos y la falta de información al paciente.',
            'duration' => 180,
            'order' => 4,
            'content' => '{"text": "Se implementarán herramientas para medir la satisfacción del cliente, como encuestas breves. Se discutirán los riesgos más comunes en la dispensación y cómo las acciones preventivas (doble chequeo, asesoría clara) impactan positivamente en la percepción del servicio y la seguridad del paciente."}',
            'video_url' => null,
            'iframe' => null,
        ],
    ],

    // Módulo 5
    5 => [
        [
            'title' => 'Devoluciones',
            'objective' => 'Gestionar devoluciones cumpliendo normatividad.',
            'description' => 'Recepción y documentación de devoluciones de clientes y proveedores.',
            'duration' => 180,
            'order' => 1,
            'content' => '{"text": "Formatos e instructivos de devoluciones."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Disposición Final',
            'objective' => 'Eliminar de forma segura medicamentos vencidos o deteriorados.',
            'description' => 'Procedimientos y alianzas con gestores autorizados.',
            'duration' => 180,
            'order' => 2,
            'content' => '{"text": "Procedimiento normativo y plan de disposición."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Indicadores, riesgos y trazabilidad',
            'objective' => 'Establecer indicadores para controlar los procesos de devolución y disposición final, y mitigar los riesgos asociados.',
            'description' => 'Medición de la eficiencia en la gestión de devoluciones y el cumplimiento normativo en la disposición final. Análisis de riesgos como la reintroducción de productos no conformes al inventario y el impacto ambiental.',
            'duration' => 180,
            'order' => 4,
            'content' => '{"text": "Se definirán KPIs como \'Porcentaje de devoluciones aceptadas vs. rechazadas\' y \'Costo de la disposición final\'. Se analizarán los riesgos de una mala gestión, asegurando la trazabilidad completa desde la devolución hasta la destrucción o retorno al proveedor, y se documentará todo el proceso para auditorías."}',
            'video_url' => null,
            'iframe' => null,
        ],
    ],

    // Módulo 6
    6 => [
        [
            'title' => 'Farmacovigilancia',
            'objective' => 'Detectar, evaluar y reportar eventos adversos.',
            'description' => 'Formatos y rutas de reporte nacional INVIMA.',
            'duration' => 180,
            'order' => 1,
            'content' => '{"text": "Estudio de caso de evento adverso."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Tecnovigilancia',
            'objective' => 'Monitorear el desempeño y seguridad de dispositivos médicos.',
            'description' => 'Procedimientos de reporte y seguimiento.',
            'duration' => 180,
            'order' => 2,
            'content' => '{"text": "Catálogo de equipos y puntos de control."}',
            'video_url' => null,
            'iframe' => null,
        ],
    ],

    // Módulo 7
    7 => [
        [
            'title' => 'Indicadores',
            'objective' => 'Definir indicadores clave de desempeño.',
            'description' => 'Formulación de KPIs para servicio farmacéutico.',
            'duration' => 180,
            'order' => 1,
            'content' => '{"text": "Matriz de indicadores y fichas técnicas."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Seguimiento y Mejora',
            'objective' => 'Analizar resultados y gestionar acciones preventivas/correctivas.',
            'description' => 'Metodologías para mejora continua.',
            'duration' => 180,
            'order' => 2,
            'content' => '{"text": "Ciclos PHVA y casos prácticos."}',
            'video_url' => null,
            'iframe' => null,
        ],
    ],

    // Módulo 8
    8 => [
        [
            'title' => 'Taller Integrador',
            'objective' => 'Elaborar mapa de procesos propio y plan de mejora.',
            'description' => 'Aplicación práctica de todos los conceptos del curso.',
            'duration' => 180,
            'order' => 1,
            'content' => '{"text": "Trabajo final guiado."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Auditoría Interna',
            'objective' => 'Realizar auditoría simulada del servicio.',
            'description' => 'Checklist y observaciones de cumplimiento.',
            'duration' => 180,
            'order' => 2,
            'content' => '{"text": "Simulación de auditoría con retroalimentación."}',
            'video_url' => null,
            'iframe' => null,
        ],
        [
            'title' => 'Plan de mejora alineado a la misión, visión y política de calidad',
            'objective' => 'Diseñar un plan de mejora continua basado en los hallazgos de la auditoría y alineado con los objetivos estratégicos de la organización.',
            'description' => 'Metodología para priorizar oportunidades de mejora, definir acciones correctivas y preventivas, asignar responsables y establecer plazos de ejecución, asegurando que cada acción contribuya a la misión y visión.',
            'duration' => 180,
            'order' => 3,
            'content' => '{"text": "En esta lección final, los participantes consolidarán los resultados de su auditoría simulada para crear un plan de mejora estructurado. Se utilizará el ciclo PHVA (Planificar, Hacer, Verificar, Actuar) como marco de trabajo para garantizar que las mejoras sean sostenibles y estén directamente vinculadas a la política de calidad de la droguería."}',
            'video_url' => null,
            'iframe' => null,
        ],
    ],
];
