<?php


return [
    [
        'apply' => true,
        'entry_id' => 'I-1.1',
        'criticality' => 'Crítico',
        'question' => 'Se cuenta con un área definida, independiente y separada, para la prestación del servicii de inyectalo-gin? ¿Los materiales que la separan, son uniformes, impermeabies, resistentes, que permiten la impieza y santización?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-1.2',
        'criticality' => 'Crítico',
        'question' => '1.2 - El área es suficiente para ofrecer comodidad al usuario y administrador? ¿El área ofrece privacidad al usuario?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-1.3',
        'criticality' => 'Crítico',
        'question' => 'Se cuenta con lavamanos en el área o cerca de ella?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-1.4',
        'criticality' => 'Mayor',
        'question' => 'Se cuenta con camilla, escalerilla y mesa auxiliar en buen estado de mantenimiento y limpieza?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-1.5',
        'criticality' => 'Crítico',
        'question' => 'Se cuenta con jeringas desechables, recipierite algodonero y cubeta, para la aplicación?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-1.6',
        'criticality' => 'Crítico',
        'question' => 'Se cuenta con jabón liquido y toallas desechables para el lavado y secado de manos?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-1.7',
        'criticality' => 'Crítico',
        'question' => 'Se cuenta con los demás materiales y dotación necesaria para el procedimiento de inyectologia? ¿Sábana para la camilla? ¿Recipientes para el manejo de residuos?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-2.1',
        'criticality' => 'Mayor',
        'question' => 'El manual de funciones del personal, establece quiénes son las personas responsables de la aplicación de inyecciones?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => [
            'document.manual-de-funciones' => 'document.details',
        ],
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-2.2',
        'criticality' => 'Crítico',
        'question' => 'El personal que administra el medicamento, cuenta con formación académica y entrenamiento que lo autoriza?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-3.1',
        'criticality' => 'Mayor',
        'question' => 'El procedimiento de limpieza de la drogueria, incluye la limpieza y sanitización del area de inyectologia? ¿Se realiza con elementos de limpieza exclusivos para esta área?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => [
            'document.limpieza-y-sanitizacion' => 'document.details',
        ],
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-3.2',
        'criticality' => 'Mayor',
        'question' => 'Se cuenta con procedimiento para la aplicación de inyecciones? ¿Se incluye las normas de boseguridad para el usuario y el administrador de la inyección?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => [
            'document.inyectologia' => 'document.details',
            'record.matriculas' => 'filament.admin.resources.quality.training.enrollments.index'
        ],
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-3.3',
        'criticality' => 'Crítico',
        'question' => 'Se verifica frente a la fórmula médica, que el medicamento, la vía, la dosis, la frecuencia y el paciente son los correctos? Únicamente via intramuscular',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => [
            'record.inyectologia' => 'por.definir',
        ],
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-4.1',
        'criticality' => 'Crítico',
        'question' => 'Se garantiza la disposición final adecuada de los residuos peligrosos generados por medio de documento formalizado con un gestor de residuos autorizado? -Contrato de ruta sanitaria-',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => [
            'folder.inyectologia' => 'etiqueta 4.1',
        ],
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-4.2',
        'criticality' => 'Crítico',
        'question' => 'Cuenta con los soportes de recolección de los residuos peligrosos por parte del gestor de residuos? -en ningún caso dicha recolección podrá ser superior a un mes-.',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => [
            'folder.inyectologia' => 'etiqueta 4.2',
        ],
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-4.3',
        'criticality' => 'Mayor',
        'question' => 'Conserva las certificaciones de disposición final que emitan los respectivos gestores de residuos peligrosos hasta por un término de cinco años?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => [
            'folder.inyectologia' => 'etiqueta 4.3',
        ],
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-4.4',
        'criticality' => 'menor',
        'question' => 'Se lleva registro de generación de residuos en el formato RH1?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => [
            'record.residuos' => 'por.definir',
        ],
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-4.5',
        'criticality' => 'Mayor',
        'question' => 'Se inutilizan los empaques y envases de medicamentos una vez se ha agotado su contenido, antes de desecharlos?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => 'I-4.6',
        'criticality' => 'Mayor',
        'question' => 'Se radicó ante Secretaria de Salud, el informe anual como generador de residuos?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => [
            'folder.inyectologia' => 'etiqueta 4.6',
        ],
        'compliance' => true,
    ],
];