<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Minutes IVC Sections
    |--------------------------------------------------------------------------
    |
    | 
    | 
    | 
    |
    */
  [
        'apply' => true,
        'entry_id' => '7.1',
        'criticality' => 'menor',
        'question' => 'Dispensación de medicamentos alopáticos',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.2',
        'criticality' => 'menor',
        'question' => 'Dispensación de medicamentos de control especial',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.3',
        'criticality' => 'menor',
        'question' => 'Dispensación de medicamentos de cadena de frío.',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.4',
        'criticality' => 'menor',
        'question' => 'Dispensación de medicamentos en preparación magistral.',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.5',
        'criticality' => 'menor',
        'question' => 'Dispensación de medicamentos homeopáticos incluidos los oficinales.',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.6',
        'criticality' => 'menor',
        'question' => 'Dispensación de dispositivos médicos.',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.7',
        'criticality' => 'menor',
        'question' => 'Venta de equipo biomédico.',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.8',
        'criticality' => 'menor',
        'question' => 'Venta de reactivos de diagnóstico.',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.9',
        'criticality' => 'menor',
        'question' => 'Dispensación de suplementos dietarios.',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.10',
        'criticality' => 'menor',
        'question' => 'Dispensacion de productos fitoterapéuticos.',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.11',
        'criticality' => 'menor',
        'question' => 'Venta de productos cosméticos.',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.12',
        'criticality' => 'menor',
        'question' => 'Venta de productos de higiene domestica -PHD',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.13',
        'criticality' => 'menor',
        'question' => 'Venta de productos absorbentes de higiene personal -PAHP',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.14',
        'criticality' => 'menor',
        'question' => 'Venta de productos no riesgosos para la vida de los usuarios',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.15',
        'criticality' => 'menor',
        'question' => 'Venta de productos no contaminantes',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.16',
        'criticality' => 'menor',
        'question' => 'Venta de droga blanca',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.17',
        'criticality' => 'menor',
        'question' => 'Venta de alimentos',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.18',
        'criticality' => 'menor',
        'question' => 'Inyectología',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.19',
        'criticality' => 'menor',
        'question' => 'Medición de glicemia',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.20',
        'criticality' => 'menor',
        'question' => 'Dispensación al Sistema General de Seguridad Social en Salud -SGSS',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
  [
        'apply' => true,
        'entry_id' => '7.21',
        'criticality' => 'menor',
        'question' => 'Atención farmacéutica',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
];