<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Minutes IVC Sections
    |--------------------------------------------------------------------------
    |
    | 
    | 
    | 
    |
    */
    [
        'apply' => true,
        'entry_id' => '0.1',
        'criticality' => 'menor',
        'question' => 'Razón social',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.2',
        'criticality' => 'menor',
        'question' => 'Nombre del Establecimiento',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.3',
        'criticality' => 'menor',
        'question' => 'NIT',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.4',
        'criticality' => 'menor',
        'question' => 'Sede',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.5',
        'criticality' => 'menor',
        'question' => 'Dirección',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.6',
        'criticality' => 'menor',
        'question' => 'Localidad',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.7',
        'criticality' => 'menor',
        'question' => 'Barrio',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.8',
        'criticality' => 'menor',
        'question' => 'Teléfono',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.9',
        'criticality' => 'menor',
        'question' => 'Correo electrónico',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.10',
        'criticality' => 'menor',
        'question' => 'Nombre del Propietario',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.11',
        'criticality' => 'menor',
        'question' => 'Tipo de Documento (Propietario)',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.13',
        'criticality' => 'menor',
        'question' => 'Número de Documento (Propietario)',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.14',
        'criticality' => 'menor',
        'question' => 'Nombre Representante Legal',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.15',
        'criticality' => 'menor',
        'question' => 'Tipo de Documento (Rep. Leg.)',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.16',
        'criticality' => 'menor',
        'question' => 'Número de Documento (Rep. Leg.)',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.17',
        'criticality' => 'menor',
        'question' => 'Dirección de Notificación',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '0.18',
        'criticality' => 'menor',
        'question' => 'Presenta Matrícula Mercantil',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => [
            [
                'key' => 'folder.cedula-establecimiento',
                'value' => 'etiqueta 0.18'
            ],
        ],
        'compliance' => true,
    ],
];
    