<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Minutes IVC Sections
    |--------------------------------------------------------------------------
    |
    | 
    | 
    | 
    |
    */
    [
        'apply' => true,
        'entry_id' => '5.1',
        'criticality' => 'Mayor',
        'question' => 'Cuenta con un área administrativa debidamente delimitada',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.2',
        'criticality' => 'Mayor',
        'question' => 'Cuenta con un área de recepción de medicamentes, dispositivos médicos, productos autorizados y materia prima?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.3',
        'criticality' => 'Mayor',
        'question' => 'Cuenta con un área de almacenamiento de medicamentos, dispositivos médicos?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.4',
        'criticality' => 'Crítico',
        'question' => 'Cuenta con área independiente y segura para el almacenamiento de medicamentos de control especial?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.5',
        'criticality' => 'Crítico',
        'question' => 'Cuenta con refrigeradores y congeladores para el almacenamiento de productos que requieren cumplir con esta condición de almacenamiento. El número de estos es proporcional al volumen si de productos que se manejan, sin que se supere su capacidad de almacenamiento?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.6',
        'criticality' => 'Mayor',
        'question' => 'Cuenta con área para el almacenamiento de las materias primas?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.7',
        'criticality' => 'Crítico',
        'question' => 'Cuenta con área especial para prestar el servicio de inyectologia y/o monitoreo de glicemia con equipo por punción?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.8',
        'criticality' => 'Crítico',
        'question' => 'Cuenta con área especial para la elaboración de preparaciones magistrales, que garantice las buenas practicas del proceso?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.9',
        'criticality' => 'Crítico',
        'question' => 'Cuenta con área especial para la atención farmacéutica?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.10.1',
        'criticality' => 'Mayor',
        'question' => 'Cuenta con un área para el almacenamiento de medicamentos fitoterapéuticos?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.10.2',
        'criticality' => 'Mayor',
        'question' => 'Cuenta con un área para el almacenamiento de suplementos dietarios?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.10.3',
        'criticality' => 'Mayor',
        'question' => 'Cuenta con un área para el almacenamiento de medicamentos homeopáticos?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.10.4',
        'criticality' => 'Mayor',
        'question' => 'Cuenta con área para el almacenamiento de los productos que no sean contaminantes ni riesgosos para la vida de los usuarios?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.11',
        'criticality' => 'Mayor',
        'question' => 'Cuenta con un área especial, debidamente identificada, para el almacenamiento transitorio de los medicamentos próximos a vencer o deteriorados (Devoluciones), que deban ser técnicamente destruidos o desnaturalizados?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.12',
        'criticality' => 'Mayor',
        'question' => 'El establecimiento cuenta con un área de dispensación de medicamentos y demás productos autorizados?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.13',
        'criticality' => 'Mayor',
        'question' => 'El establecimiento cuenta con un área de cuarentena de medicamentos (en ella también se pueden almacenar de manera transitoria los productos retirados del mercado)?',
        'answer' => '',
        'entry_type' => 'boolean',
        'links' => null,
        'compliance' => true,
    ],
];