<?php

use App\Models\MinutesIvcSectionEntry as EntryType;

return [

    /*
    |--------------------------------------------------------------------------
    | Minutes IVC Sections
    |--------------------------------------------------------------------------
    */
    '2.1 Información Talento Humano' => [
        '2.1.1 Identificación del Director Técnico' => [
            [
                'apply' => true,
                'entry_id' => '2.1.1.1',
                'criticality' => 'menor',
                'question' => 'Nombre',
                'answer' => '',
                'entry_type' => EntryType::TEXT,
                'links' => null,
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.1.2',
                'criticality' => 'menor',
                'question' => 'Tipo de documento',
                'answer' => '',
                'entry_type' => EntryType::TEXT,
                'links' => null,
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.1.3',
                'criticality' => 'menor',
                'question' => 'Número del documento',
                'answer' => '',
                'entry_type' => EntryType::FOLDER,
                'links' => [
                    [
                        'key' => 'etiqueta',
                        'value' => '2.1.1.3'
                    ],
                ],
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.1.4',
                'criticality' => 'Crítico',
                'question' => 'Título o Permiso',
                'answer' => '',
                'entry_type' => EntryType::TEXT,
                'links' => null,
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.1.5',
                'criticality' => 'menor',
                'question' => 'No. del Título o Registro',
                'answer' => '',
                'entry_type' => EntryType::FOLDER,
                'links' => [
                    [
                        'key' => 'etiqueta',
                        'value' => '2.1.1.5'
                    ],
                ],
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.1.6',
                'criticality' => 'menor',
                'question' => 'Título expedido por',
                'answer' => '',
                'entry_type' => EntryType::TEXT,
                'links' => null,
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.1.7',
                'criticality' => 'menor',
                'question' => 'Fecha de expedición del título',
                'answer' => '',
                'entry_type' => EntryType::TEXT,
                'links' => null,
                'compliance' => true,
            ],
        ],
        '2.1.2 Identificación del Delegado Responsable' => [
            [
                'apply' => true,
                'entry_id' => '2.1.2.1',
                'criticality' => 'menor',
                'question' => 'Nombre',
                'answer' => '',
                'entry_type' => EntryType::TEXT,
                'links' => null,
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.2.2',
                'criticality' => 'menor',
                'question' => 'Tipo de Doc. de Ident. Delegado del D.T.',
                'answer' => '',
                'entry_type' => EntryType::TEXT,
                'links' => null,
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.2.3',
                'criticality' => 'menor',
                'question' => 'Número de Documento',
                'answer' => '',
                'entry_type' => EntryType::TEXT,
                'links' => null,
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.2.4',
                'criticality' => 'Mayor',
                'question' => 'Título o Permiso del Delegado',
                'answer' => '',
                'entry_type' => EntryType::TEXT,
                'links' => null,
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.2.5',
                'criticality' => 'menor',
                'question' => 'Número del título o permiso',
                'answer' => '',
                'entry_type' => EntryType::FOLDER,
                'links' => [
                    [
                        'key' => 'etiqueta',
                        'value' => '2.1.2.5'
                    ],
                ],
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.2.6',
                'criticality' => 'menor',
                'question' => 'Título expedido por',
                'answer' => '',
                'entry_type' => EntryType::TEXT,
                'links' => null,
                'compliance' => true,
            ],
            [
                'apply' => true,
                'entry_id' => '2.1.2.7',
                'criticality' => 'menor',
                'question' => 'Fecha de expedición del título',
                'answer' => '',
                'entry_type' => EntryType::TEXT,
                'links' => null,
                'compliance' => true,
            ],
        ],
        '2.1.3 Identificación del personal dispensador' => [
            '2.1.3.1 Dispensador 1' => [
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.1',
                    'criticality' => 'menor',
                    'question' => 'Nombre',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.2',
                    'criticality' => 'menor',
                    'question' => 'Tipo de Doc. Ident. del dispensador',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.3',
                    'criticality' => 'menor',
                    'question' => 'Número de Documento',
                    'answer' => '',
                    'entry_type' => EntryType::FOLDER,
                    'links' => [
                        [
                            'key' => 'etiqueta',
                            'value' => '2.1.3.1.3'
                        ],
                    ],
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.4',
                    'criticality' => 'Mayor',
                    'question' => 'Título o Permiso del Delegado',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.5',
                    'criticality' => 'menor',
                    'question' => 'Número del título o permiso',
                    'answer' => '',
                    'entry_type' => EntryType::FOLDER,
                    'links' => [
                        [
                            'key' => 'etiqueta',
                            'value' => '2.1.3.5'
                        ],
                    ],
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.6',
                    'criticality' => 'menor',
                    'question' => 'Título expedido por',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.7',
                    'criticality' => 'menor',
                    'question' => 'Fecha de expedición del título',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
            ],
            '2.1.3.2 Dispensador 2' => [
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.1',
                    'criticality' => 'menor',
                    'question' => 'Nombre',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.2',
                    'criticality' => 'menor',
                    'question' => 'Tipo de Doc. Ident. del dispensador',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.3',
                    'criticality' => 'menor',
                    'question' => 'Número de Documento',
                    'answer' => '',
                    'entry_type' => EntryType::FOLDER,
                    'links' => [
                        [
                            'key' => 'etiqueta',
                            'value' => '2.1.3.1.3'
                        ],
                    ],
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.4',
                    'criticality' => 'Mayor',
                    'question' => 'Título o Permiso del Delegado',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.5',
                    'criticality' => 'menor',
                    'question' => 'Número del título o permiso',
                    'answer' => '',
                    'entry_type' => EntryType::FOLDER,
                    'links' => [
                        [
                            'key' => 'etiqueta',
                            'value' => '2.1.3.5'
                        ],
                    ],
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.6',
                    'criticality' => 'menor',
                    'question' => 'Título expedido por',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.7',
                    'criticality' => 'menor',
                    'question' => 'Fecha de expedición del título',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
            ],
            '2.1.3.3 Dispensador 3' => [
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.1',
                    'criticality' => 'menor',
                    'question' => 'Nombre',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.2',
                    'criticality' => 'menor',
                    'question' => 'Tipo de Doc. Ident. del dispensador',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.3',
                    'criticality' => 'menor',
                    'question' => 'Número de Documento',
                    'answer' => '',
                    'entry_type' => EntryType::FOLDER,
                    'links' => [
                        [
                            'key' => 'etiqueta',
                            'value' => '2.1.3.1.3'
                        ],
                    ],
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.4',
                    'criticality' => 'Mayor',
                    'question' => 'Título o Permiso del Delegado',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.5',
                    'criticality' => 'menor',
                    'question' => 'Número del título o permiso',
                    'answer' => '',
                    'entry_type' => EntryType::FOLDER,
                    'links' => [
                        [
                            'key' => 'etiqueta',
                            'value' => '2.1.3.5'
                        ],
                    ],
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.6',
                    'criticality' => 'menor',
                    'question' => 'Título expedido por',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.7',
                    'criticality' => 'menor',
                    'question' => 'Fecha de expedición del título',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
            ],
            '2.1.3.4 Dispensador 4' => [
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.1',
                    'criticality' => 'menor',
                    'question' => 'Nombre',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.2',
                    'criticality' => 'menor',
                    'question' => 'Tipo de Doc. Ident. del dispensador',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.3',
                    'criticality' => 'menor',
                    'question' => 'Número de Documento',
                    'answer' => '',
                    'entry_type' => EntryType::FOLDER,
                    'links' => [
                        [
                            'key' => 'etiqueta',
                            'value' => '2.1.3.1.3'
                        ],
                    ],
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.4',
                    'criticality' => 'Mayor',
                    'question' => 'Título o Permiso del Delegado',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.5',
                    'criticality' => 'menor',
                    'question' => 'Número del título o permiso',
                    'answer' => '',
                    'entry_type' => EntryType::FOLDER,
                    'links' => [
                        [
                            'key' => 'etiqueta',
                            'value' => '2.1.3.5'
                        ],
                    ],
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.6',
                    'criticality' => 'menor',
                    'question' => 'Título expedido por',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.7',
                    'criticality' => 'menor',
                    'question' => 'Fecha de expedición del título',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
            ],
            '2.1.3.5 Dispensador 5' => [
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.1',
                    'criticality' => 'menor',
                    'question' => 'Nombre',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.2',
                    'criticality' => 'menor',
                    'question' => 'Tipo de Doc. Ident. del dispensador',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.3',
                    'criticality' => 'menor',
                    'question' => 'Número de Documento',
                    'answer' => '',
                    'entry_type' => EntryType::FOLDER,
                    'links' => [
                        [
                            'key' => 'etiqueta',
                            'value' => '2.1.3.1.3'
                        ],
                    ],
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.4',
                    'criticality' => 'Mayor',
                    'question' => 'Título o Permiso del Delegado',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.5',
                    'criticality' => 'menor',
                    'question' => 'Número del título o permiso',
                    'answer' => '',
                    'entry_type' => EntryType::FOLDER,
                    'links' => [
                        [
                            'key' => 'etiqueta',
                            'value' => '2.1.3.5'
                        ],
                    ],
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.6',
                    'criticality' => 'menor',
                    'question' => 'Título expedido por',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
                [
                    'apply' => true,
                    'entry_id' => '2.1.3.1.7',
                    'criticality' => 'menor',
                    'question' => 'Fecha de expedición del título',
                    'answer' => '',
                    'entry_type' => EntryType::TEXT,
                    'links' => null,
                    'compliance' => true,
                ],
            ],
        ],
    ],
    '2.2 Principios y generalidades' => [
        [
            'apply' => true,
            'entry_id' => '2.2.1',
            'criticality' => 'critico',
            'question' => '¿Cuenta con Director Técnico con perfil acorde a la normatividad?',
            'answer' => '',
            'entry_type' => EntryType::TEXT,
            'links' => null,
            'compliance' => true,
        ],
        [
            'apply' => true,
            'entry_id' => '2.2.2',
            'criticality' => 'menor',
            'question' => '¿Cuenta con soporte que evidencie la contratación para el Director Técnico?',
            'answer' => '',
            'entry_type' => EntryType::FOLDER,
            'links' => [
                [
                    'key' => 'recursos-humanos',
                    'value' => 'etiqueta 2.2.2'
                ]
            ],
            'compliance' => true,
        ],
        [
            'apply' => true,
            'entry_id' => '2.2.3',
            'criticality' => 'menor',
            'question' => '¿Se evidencia soporte de las funciones u obligaciones, lugar de trabajo y tiempo de permanencia del Director Técnico?',
            'answer' => '',
            'entry_type' => EntryType::ROUTE,
            'links' => [
                [
                    'key' => 'document.slug',
                    'value' => 'manual-funciones'
                ],
            ],
            'compliance' => true,
        ],
        [
            'apply' => true,
            'entry_id' => '2.2.4',
            'criticality' => 'menor',
            'question' => '¿Existen soportes que evidencien cómo suplir las ausencias temporales y justificadas del Director Técnico?',
            'answer' => '',
            'entry_type' => EntryType::ROUTE,
            'links' => [
                [
                    'key' => 'document.slug',
                    'value' => 'delegacion-funciones-dt'
                ],
            ],
            'compliance' => true,
        ],
    ],
];
