<?php

return [
    [
        'apply' => true,
        'entry_id' => '8.1',
        'criticality' => 'Crítico',
        'question' => '¿El establecimiento contratado para la prestación de servicios dentro del SGSSS participa en el programa de farmacovigilancia correspondiente?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '8.2',
        'criticality' => 'Mayor',
        'question' => '¿Se cuenta con vínculo con una EAPB, para el suministro de medicamentos al SGSSS?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '8.3',
        'criticality' => 'Crítico',
        'question' => '¿Los productos con la leyenda de "Uso Institucional, Prohibida su Venta", se almacenan indepen-dientemente de los productos comerciales?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '8.4',
        'criticality' => 'menor',
        'question' => '¿Cuenta con anuncio claro y destacado al interior del local, referente a los Espacios libres de Humo?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '8.5',
        'criticality' => 'Mayor',
        'question' => '¿Cuenta con anuncio claro y destacado al interior del local, referente a "Prohibida la venta de alcohol industrial y antiséptico a niños, niñas y adolescentes. Ingerirlo puede generar graves efectos sobre la salud, incluso la muerte"?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '8.6',
        'criticality' => 'Mayor',
        'question' => '¿Se garantiza el cumplimiento de las condiciones y advertencias establecidas por el fabricante en 8.6. el empaque y etiqueta de los productos?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '8.7',
        'criticality' => 'Mayor',
        'question' => '¿En el establecimiento, solo se cuenta con áreas y se desarrollan procedimientos propios del 8.7. servicio o establecimiento farmacéutico? (No está permitida la preparación de alimentos, la consulta médica, la aplicación de procedimientos médicos o estéticos)',
        'answer' => '',
        'entry_type' => 'text',
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '8.8',
        'criticality' => 'Mayor',
        'question' => '¿Se informó oportunamente de la apertura, cambio de direccion, direccion tecnica o propietario del Servicio / Establecimiento Farmaceutico, a la Secretaria de Salud?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => [
            'folder.otros-aspectos' => 'etiqueta 8.8',
        ],
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '8.9',
        'criticality' => 'Mayor',
        'question' => '¿El personal de la drogueria (Director Tecnico y Auxiliares), han asistido a la capacitacion brindada por la Secretaría Distrital de Salud?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => [
            'folder.otros-aspectos' => 'etiqueta 8.9',
        ],
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '8.10',
        'criticality' => 'menor',
        'question' => '¿El establecimiento cuenta con un plan de capacitación de por lo menos 10 horas anuales, continuo y permanente para el personal manipulador de alimentos?',
        'answer' => '',
        'entry_type' => 'text',
        'links' => [
            'folder.otros-aspectos' => 'etiqueta 8.10',
        ],
        'compliance' => true,
    ],
];
