<?php

use App\Models\MinutesIvcSectionEntry as EntryType;

return [

    /*
    |--------------------------------------------------------------------------
    | Minutes IVC Sections
    |--------------------------------------------------------------------------
    */
    [
        'apply' => true,
        'entry_id' => '5.1',
        'criticality' => 'Mayor',
        'question' => 'Área administrativa',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.2',
        'criticality' => 'Mayor',
        'question' => 'Área de recepción técnica',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.3',
        'criticality' => 'Mayor',
        'question' => 'Área de cuarentena',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.4',
        'criticality' => 'Crítico',
        'question' => 'Área de almacenamiento',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.4.1',
        'criticality' => 'Crítico',
        'question' => 'Área de almacenamiento de medicamentos de control especial',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.4.2',
        'criticality' => 'Crítico',
        'question' => 'Área de almacenamiento de medicamentos que requieran cadena de frío',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.5',
        'criticality' => 'Mayor',
        'question' => 'Área de dispensación',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.6',
        'criticality' => 'menor',
        'question' => 'Área de Rechazos, Devoluciones, Retiros del mercado',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.7',
        'criticality' => 'menor',
        'question' => 'Áera de residuos',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.8',
        'criticality' => 'Crítico',
        'question' => 'Área para prestar el servicio de inyectología',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.9',
        'criticality' => 'Crítico',
        'question' => 'Área para prestar el servicio de monitoreo de glicemia con equipo por punción',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.10',
        'criticality' => 'Crítico',
        'question' => 'Área para la elaboración de preparaciones magistrales',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
    [
        'apply' => true,
        'entry_id' => '5.11',
        'criticality' => 'Crítico',
        'question' => 'Área para atención farmacéutica',
        'answer' => '',
        'entry_type' => EntryType::TEXT,
        'links' => null,
        'compliance' => true,
    ],
];


