<?php

return [

    'default_risks' => [
        [
            'code' => 'RISK-AR-001',
            'process_code' => 'A-AR',
            'process_name' => 'Asuntos Regulatorios',
            'title' => 'Desactualizacion de requisitos legales y sanitarios aplicables',
            'activity' => 'Seguimiento normativo y documental',
            'description' => 'Incumplimiento de requisitos sanitarios, legales o documentales exigibles a la drogueria o al servicio farmaceutico.',
            'cause' => 'Falta de seguimiento a cambios normativos, ausencia de cronograma de renovaciones y control documental debil.',
            'consequence' => 'Hallazgos en visitas IVC, medidas sanitarias, sanciones, reprocesos y afectacion de la continuidad del servicio.',
            'risk_type' => 'regulatorio',
            'impact_area' => 'regulatorio',
            'existing_controls' => 'Carpeta legal, revision periodica de actos administrativos, listas de chequeo de visita y control de vencimientos documentales.',
            'probability' => 3,
            'impact' => 5,
            'residual_probability' => 2,
            'residual_impact' => 4,
            'treatment_plan' => 'Mantener matriz legal vigente, asignar responsable y frecuencia de revision, verificar soportes antes de visitas y gestionar acciones correctivas ante hallazgos. En clave ISO 9001, fortalecer el control de informacion documentada y el enfoque basado en riesgos.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '6.1, 7.5, 9.1, 10.2',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Decreto 2200 de 2005 y Resolucion 1403 de 2007',
            ],
        ],
        [
            'code' => 'RISK-SL-001',
            'process_code' => 'M-SL',
            'process_name' => 'Seleccion',
            'title' => 'Portafolio de medicamentos no alineado con la demanda real',
            'activity' => 'Definicion y actualizacion del listado basico',
            'description' => 'Seleccion deficiente de productos esenciales o de alta rotacion para la poblacion atendida.',
            'cause' => 'Analisis insuficiente de consumos, perfil epidemiologico incompleto y decisiones de compra sin datos confiables.',
            'consequence' => 'Desabastecimientos, perdida de ventas, insatisfaccion del usuario y aumento de compras urgentes.',
            'risk_type' => 'operacional',
            'impact_area' => 'operativo',
            'existing_controls' => 'Listado basico, revision de faltantes, analisis de rotacion y retroalimentacion desde dispensacion.',
            'probability' => 4,
            'impact' => 4,
            'residual_probability' => 2,
            'residual_impact' => 3,
            'treatment_plan' => 'Revisar periodicamente el portafolio con datos de consumo, estacionalidad, medicamentos esenciales y PQRS por no disponibilidad. ISO 9001: usar evidencia para la toma de decisiones y revisar riesgos y oportunidades del proceso.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '4.1, 6.1, 9.1, 9.3',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Gestion del servicio farmaceutico orientada a oportunidad y disponibilidad',
            ],
        ],
        [
            'code' => 'RISK-AQ-001',
            'process_code' => 'M-AQ',
            'process_name' => 'Adquisicion',
            'title' => 'Compra a proveedor no autorizado o con desempeno deficiente',
            'activity' => 'Seleccion y seguimiento de proveedores',
            'description' => 'Adquisicion de medicamentos o dispositivos a proveedores que no cumplen requisitos legales, tecnicos o logisticos.',
            'cause' => 'Ausencia de evaluacion de proveedores, urgencias de compra y falta de criterios documentados para homologacion.',
            'consequence' => 'Ingreso de productos no conformes, retrasos en entrega, afectacion de la trazabilidad y mayor exposicion regulatoria.',
            'risk_type' => 'calidad',
            'impact_area' => 'producto',
            'existing_controls' => 'Listado de proveedores aprobados, ordenes de compra, verificacion documental y evaluacion periodica.',
            'probability' => 3,
            'impact' => 5,
            'residual_probability' => 2,
            'residual_impact' => 3,
            'treatment_plan' => 'Definir criterios de seleccion, reevaluar proveedores por calidad y cumplimiento, bloquear proveedores no conformes y exigir soportes sanitarios vigentes. ISO 9001: reforzar el control de procesos externos y la evaluacion de desempeno.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '8.4, 8.6, 9.1',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Compras solo a proveedores habilitados y con soportes verificables',
            ],
        ],
        [
            'code' => 'RISK-RT-001',
            'process_code' => 'M-RT',
            'process_name' => 'Recepcion Tecnica',
            'title' => 'Ingreso de productos no conformes por fallas en recepcion tecnica',
            'activity' => 'Recepcion administrativa y tecnica de medicamentos',
            'description' => 'Aceptacion de productos con empaque deteriorado, vencimiento corto, rotulado deficiente, cadena de frio comprometida o soporte inconsistente.',
            'cause' => 'Recepcion apresurada, listas de chequeo incompletas, personal no entrenado y ausencia de criterio de rechazo.',
            'consequence' => 'Riesgo sanitario, devoluciones, inmovilizacion de inventario, errores de dispensacion y hallazgos regulatorios.',
            'risk_type' => 'sanitario',
            'impact_area' => 'producto',
            'existing_controls' => 'Acta de recepcion, verificacion contra orden de compra y factura, inspeccion visual y criterios de aceptacion/rechazo.',
            'probability' => 3,
            'impact' => 5,
            'residual_probability' => 2,
            'residual_impact' => 3,
            'treatment_plan' => 'Estandarizar lista de chequeo de recepcion, entrenar al personal, definir cuarentena para productos dudosos y registrar no conformidades para analisis de causa. ISO 9001: fortalecer control operacional y liberacion del producto solo cuando cumpla criterios.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '8.5.1, 8.6, 8.7, 10.2',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Recepcion tecnica conforme al modelo de gestion del servicio farmaceutico',
            ],
        ],
        [
            'code' => 'RISK-AT-001',
            'process_code' => 'M-AT',
            'process_name' => 'Almacenamiento',
            'title' => 'Desviacion de temperatura, humedad o cadena de frio',
            'activity' => 'Monitoreo de condiciones ambientales',
            'description' => 'Conservacion de medicamentos fuera de rangos permitidos por fallas en monitoreo, equipos o respuesta ante alertas.',
            'cause' => 'Equipos sin mantenimiento, registros incompletos, termometros no verificados y ausencia de contingencia.',
            'consequence' => 'Perdida de calidad del producto, devoluciones, cuarentena, inmovilizacion de stock y afectacion al paciente.',
            'risk_type' => 'sanitario',
            'impact_area' => 'infraestructura',
            'existing_controls' => 'Registros diarios de temperatura y humedad, nevera exclusiva, termometros y planillas de control ambiental.',
            'probability' => 4,
            'impact' => 5,
            'residual_probability' => 2,
            'residual_impact' => 3,
            'treatment_plan' => 'Definir rangos por categoria de producto, usar alarmas o verificaciones dobles, mantener equipos y activar plan de contingencia ante desviaciones. ISO 9001: asegurar infraestructura, recursos de seguimiento y respuesta basada en evidencias.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '7.1.3, 7.1.5, 8.5.4, 8.7',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Control ambiental y cadena de frio en medicamentos termolabiles',
            ],
        ],
        [
            'code' => 'RISK-AT-002',
            'process_code' => 'M-AT',
            'process_name' => 'Almacenamiento',
            'title' => 'Vencimientos y deterioro por mala rotacion FEFO/PEPS',
            'activity' => 'Ubicacion, rotacion y control de fechas de vencimiento',
            'description' => 'Permanencia excesiva de productos en estanteria o nevera por mala rotacion y seguimiento insuficiente a fechas de vencimiento.',
            'cause' => 'Inventario desactualizado, rotulacion deficiente, ausencia de barridos periodicos y sobrestock.',
            'consequence' => 'Perdidas economicas, devoluciones tardias, desabastecimiento indirecto y riesgo de dispensar producto no apto.',
            'risk_type' => 'logistico',
            'impact_area' => 'financiero',
            'existing_controls' => 'Listados de proximos a vencer, rotacion FEFO/PEPS, senalizacion de cuarentena y revisiones de estanteria.',
            'probability' => 4,
            'impact' => 4,
            'residual_probability' => 2,
            'residual_impact' => 3,
            'treatment_plan' => 'Programar barridos de vencimientos, separar productos proximos a vencer, ajustar compras y analizar causas de sobrestock. ISO 9001: usar seguimiento del desempeno e implementar acciones correctivas sobre no conformidades recurrentes.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '8.5.4, 8.7, 9.1, 10.2',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Gestion preventiva de vencimientos y devoluciones a proveedor',
            ],
        ],
        [
            'code' => 'RISK-GI-001',
            'process_code' => 'A-GI',
            'process_name' => 'Gestion de Inventarios',
            'title' => 'Diferencias de inventario y trazabilidad incompleta',
            'activity' => 'Registro y conciliacion de movimientos',
            'description' => 'Existencias fisicas, lotes o fechas de vencimiento no coinciden con el sistema o los registros manuales.',
            'cause' => 'Registros tardios, fallas del sistema, ajustes sin soporte, conteos infrecuentes y poco control de lotes.',
            'consequence' => 'Compras erradas, desabastecimiento, sobrestock, perdida de trazabilidad y dificultad para responder a retiros o auditorias.',
            'risk_type' => 'tecnologico',
            'impact_area' => 'operativo',
            'existing_controls' => 'Kardex o software, conteos ciclicos, conciliaciones y soportes de ajustes de inventario.',
            'probability' => 4,
            'impact' => 4,
            'residual_probability' => 2,
            'residual_impact' => 3,
            'treatment_plan' => 'Estandarizar el registro de movimientos, revisar permisos de ajuste, hacer conciliaciones ciclicas y definir respaldo operativo ante caidas del sistema. ISO 9001: asegurar integridad de la informacion, seguimiento del desempeno y control de cambios.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '7.1.3, 7.1.5, 8.5.2, 9.1',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Trazabilidad de lotes y existencias para control sanitario y operativo',
            ],
        ],
        [
            'code' => 'RISK-DP-001',
            'process_code' => 'M-DP',
            'process_name' => 'Dispensacion',
            'title' => 'Error de dispensacion por medicamento, dosis o paciente equivocado',
            'activity' => 'Validacion de formula y entrega al usuario',
            'description' => 'Dispensacion incorrecta asociada a confusion LASA, validacion incompleta de la formula o interrupciones durante la atencion.',
            'cause' => 'Sobrecarga operativa, doble verificacion inexistente, almacenamiento confuso y capacitacion insuficiente.',
            'consequence' => 'Afectacion de la seguridad del paciente, devoluciones, eventos adversos, PQRS y deterioro reputacional.',
            'risk_type' => 'seguridad',
            'impact_area' => 'paciente',
            'existing_controls' => 'Validacion de formula, separacion de productos de alto riesgo, apoyo visual para LASA y orientacion al usuario.',
            'probability' => 4,
            'impact' => 5,
            'residual_probability' => 2,
            'residual_impact' => 4,
            'treatment_plan' => 'Aplicar doble verificacion para medicamentos de alto riesgo y LASA, mejorar senalizacion, reducir interrupciones y registrar incidentes y casi fallas. ISO 9001: controlar la prestacion del servicio, preservar la salida conforme y actuar sobre no conformidades.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '8.5.1, 8.5.4, 8.7, 10.2',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Uso seguro de medicamentos y enfoque de seguridad del paciente',
            ],
        ],
        [
            'code' => 'RISK-DP-002',
            'process_code' => 'M-DP',
            'process_name' => 'Dispensacion',
            'title' => 'Orientacion insuficiente al usuario sobre uso seguro del medicamento',
            'activity' => 'Educacion al usuario en el momento de la dispensacion',
            'description' => 'Entrega del medicamento sin informacion clara sobre dosis, horarios, conservacion, advertencias o signos de alarma.',
            'cause' => 'Falta de tiempo, ausencia de guiones de orientacion y enfoque excesivo en la transaccion comercial.',
            'consequence' => 'Mala adherencia, uso inadecuado, reconsultas, PQRS y menor satisfaccion del usuario.',
            'risk_type' => 'calidad',
            'impact_area' => 'paciente',
            'existing_controls' => 'Consejeria basica, etiquetado, material educativo y preguntas de verificacion de entendimiento.',
            'probability' => 3,
            'impact' => 4,
            'residual_probability' => 2,
            'residual_impact' => 2,
            'treatment_plan' => 'Definir mensajes minimos obligatorios por tipo de medicamento, capacitar al personal en comunicacion clara y verificar comprension del usuario. ISO 9001: reforzar competencia, comunicacion con el cliente y control del servicio orientado al usuario.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '7.2, 7.4, 8.2.1, 8.5.1',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Promocion del uso adecuado y racional del medicamento',
            ],
        ],
        [
            'code' => 'RISK-DV-001',
            'process_code' => 'M-DV',
            'process_name' => 'Devoluciones y Disposicion Final',
            'title' => 'Manejo inadecuado de devoluciones, vencidos y residuos',
            'activity' => 'Clasificacion, cuarentena y disposicion final',
            'description' => 'Productos vencidos, averiados o devueltos se mezclan con inventario util o se disponen sin trazabilidad suficiente.',
            'cause' => 'Segregacion deficiente, falta de actas, desconocimiento del procedimiento y seguimiento insuficiente al gestor externo.',
            'consequence' => 'Riesgo sanitario y ambiental, hallazgos regulatorios, perdidas economicas y reprocesos.',
            'risk_type' => 'sanitario',
            'impact_area' => 'ambiente',
            'existing_controls' => 'Area de cuarentena, actas de devolucion, identificacion de residuos y relacion con gestor autorizado.',
            'probability' => 3,
            'impact' => 5,
            'residual_probability' => 2,
            'residual_impact' => 3,
            'treatment_plan' => 'Fortalecer segregacion y rotulacion, documentar cadena de custodia, verificar soportes del gestor y auditar la disposicion final. ISO 9001: asegurar preservacion de salidas no conformes, trazabilidad y acciones correctivas.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '8.5.2, 8.7, 9.1, 10.2',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Disposicion segura de medicamentos vencidos y residuos del servicio farmaceutico',
            ],
        ],
        [
            'code' => 'RISK-RH-001',
            'process_code' => 'A-RH',
            'process_name' => 'Gestion de Recurso Humano',
            'title' => 'Personal sin competencia suficiente para procesos criticos',
            'activity' => 'Induccion, entrenamiento y seguimiento al desempeno',
            'description' => 'El personal que participa en recepcion, almacenamiento o dispensacion no cuenta con entrenamiento suficiente o actualizado.',
            'cause' => 'Induccion incompleta, alta rotacion, ausencia de evaluacion de competencias y capacitacion no planificada.',
            'consequence' => 'Errores operativos, incumplimientos regulatorios, incidentes con pacientes y variabilidad en la ejecucion de procesos.',
            'risk_type' => 'operacional',
            'impact_area' => 'operativo',
            'existing_controls' => 'Perfiles de cargo, cronograma de capacitacion, evaluaciones de desempeno y registros de induccion.',
            'probability' => 4,
            'impact' => 4,
            'residual_probability' => 2,
            'residual_impact' => 3,
            'treatment_plan' => 'Definir matriz de competencias, cerrar brechas con induccion y reinduccion, evaluar efectividad de la formacion y supervisar tareas criticas. ISO 9001: fortalecer competencia, toma de conciencia y control operacional del talento humano.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '7.1.2, 7.2, 7.3, 8.5.1',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Idoneidad del talento humano del servicio farmaceutico',
            ],
        ],
        [
            'code' => 'RISK-GC-001',
            'process_code' => 'A-GC',
            'process_name' => 'Gestion de Calidad',
            'title' => 'No conformidades, incidentes y PQRS sin cierre efectivo',
            'activity' => 'Analisis, mejora y seguimiento',
            'description' => 'Hallazgos, errores, incidentes o quejas se registran, pero no generan acciones eficaces o seguimiento suficiente.',
            'cause' => 'Analisis superficial de causa raiz, indicadores poco usados y ausencia de responsables o fechas de cierre.',
            'consequence' => 'Repeticion de fallas, desgaste operativo, insatisfaccion del usuario y bajo aprendizaje organizacional.',
            'risk_type' => 'calidad',
            'impact_area' => 'operativo',
            'existing_controls' => 'Planes de mejora, auditorias internas, seguimiento a PQRS e indicadores de calidad.',
            'probability' => 3,
            'impact' => 4,
            'residual_probability' => 2,
            'residual_impact' => 2,
            'treatment_plan' => 'Aplicar metodologia de causa raiz, definir responsables y fechas, verificar eficacia de acciones y presentar resultados en revision por la direccion. ISO 9001: reforzar evaluacion del desempeno, mejora continua y tratamiento de no conformidades.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '9.1, 9.2, 9.3, 10.2, 10.3',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Mejora continua del sistema de gestion de calidad en droguerias y servicios farmaceuticos',
            ],
        ],
        [
            'code' => 'RISK-PG-001',
            'process_code' => 'D-PG',
            'process_name' => 'Planeacion y Gerencia',
            'title' => 'Gestion del riesgo desconectada de la planeacion y los indicadores',
            'activity' => 'Revision por la direccion y seguimiento estrategico',
            'description' => 'La matriz de riesgos existe, pero no se revisa con la frecuencia requerida ni se usa para priorizar recursos y acciones.',
            'cause' => 'Revision por la direccion irregular, objetivos sin seguimiento y enfoque reactivo ante incidentes o visitas.',
            'consequence' => 'Decisiones tardias, controles debiles, dispersion de esfuerzos y baja madurez del sistema de calidad.',
            'risk_type' => 'calidad',
            'impact_area' => 'operativo',
            'existing_controls' => 'Indicadores, planes de accion, comites de seguimiento y matriz de riesgos institucional.',
            'probability' => 3,
            'impact' => 4,
            'residual_probability' => 2,
            'residual_impact' => 2,
            'treatment_plan' => 'Revisar la matriz de riesgos en comites de gestion, vincularla con indicadores y presupuesto, y actualizarla ante cambios del contexto. ISO 9001: integrar riesgos y oportunidades en la planeacion, seguimiento y revision por la direccion.',
            'status' => 'en_tratamiento',
            'data' => [
                'iso_9001_clause' => '4.1, 6.1, 9.1, 9.3, 10.3',
                'treatment_strategy' => 'mitigar',
                'contexto_colombia' => 'Enfoque preventivo para sostenibilidad del servicio farmaceutico',
            ],
        ],
    ],

];
